# Build configuration options

# Backend toggles
set(HPC_ENABLE_SIMD ON)
set(HPC_ENABLE_OPENMP ON)
set(HPC_ENABLE_MPI OFF)
set(HPC_ENABLE_CUDA OFF)

# BLAS/LAPACK options
set(HPC_ENABLE_CUBLAS OFF)
set(HPC_ENABLE_OPENBLAS OFF)
set(HPC_ENABLE_ACCELERATE OFF)

# Python options
set(HPC_ENABLE_PYBIND11 OFF)
set(HPC_ENABLE_PYTORCH OFF)

# Compilation options
set(HPC_USE_CCACHE ON)
set(HPC_USE_HIGH_LEVEL_OPTIMIZATIONS ON)

# Application options
set(HPC_ENABLE_BENCHMARKING ON)
